name: CI

on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
   style:
     runs-on: ubuntu-20.04
     container:
       image: ghcr.io/scientificcomputing/fenics:2024-05-28
       options: --privileged
     name: Hippylib test

     steps:
        - name: Fix ufl
          run: ln -s /usr/lib/python3/dist-packages/ufl_legacy/ /usr/lib/python3/dist-packages/ufl 
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Import hippylib
          run: python3 -c 'import hippylib' && pwd && ls
        - name: Unit test
          run: source .github/workflows/run_unittest.sh
        - name: Test applications
          run:  source .github/workflows/run_applications.sh
        - name: Run notebooks
          run: source .github/workflows/run_notebooks.sh

